# Generated by Django 4.2.2 on 2023-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(null=True, upload_to='menu/templates/images'),
        ),
    ]
