# Generated by Django 4.2.2 on 2023-06-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
    ]
