# Generated by Django 4.2.2 on 2023-11-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_comment_created_at_comment_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
