# Generated by Django 4.2.2 on 2023-11-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_favouritemeals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteMeals',
            new_name='FavouriteMeal',
        ),
    ]
