# Generated by Django 4.2.2 on 2023-11-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_favouritemeals_favouritemeal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteMeal',
            new_name='FavoriteMeal',
        ),
    ]
