# Generated by Django 4.2.2 on 2023-12-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_favouritemeal_favoritemeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='calories',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='carbohydrates',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='fats',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='is_vegan',
        #     field=models.BooleanField(default=False),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='mass',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='meal',
        #     name='proteins',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='meal',
        #     name='description',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
