# Generated by Django 4.2.2 on 2023-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_favouritemeal_favoritemeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_vegan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='mass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.IntegerField(null=True),
        ),
    ]
