# Generated by Django 4.2.2 on 2023-12-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_mealcategory_meal_calories_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.mealcategory'),
        ),
    ]
