# Generated by Django 4.2.2 on 2023-12-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_mealcategory_meal_calories_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.mealcategory'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
