# Generated by Django 4.2.2 on 2023-12-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_mealcategory_meal_calories_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_vegan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='mass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
