# Generated by Django 4.2.2 on 2023-12-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_meal_category_alter_mealcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(db_column='category_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.mealcategory', to_field='name'),
        ),
    ]
