# Generated by Django 4.2.2 on 2024-04-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_meal_category'),
        ('menu', '0016_alter_meal_category'),
    ]

    operations = [
    ]
