# Generated by Django 4.2.2 on 2024-04-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_merge_0013_meal_category_0016_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.mealcategory', to_field='name'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
